#!/usr/bin/env python3
"""
Final migration script using Supabase REST API
Loads order_items and inventory_transactions
"""

import os
import re
import json
import time
import requests
from pathlib import Path

# Supabase configuration
SUPABASE_URL = "https://onnncepenxxxfprqaodu.supabase.co"
SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ubm5jZXBlbnh4eGZwcnFhb2R1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjQ4MTk4NywiZXhwIjoyMDg4MDU3OTg3fQ.z0vhXCfPqFmN13kA0bJYu1xDBMQVxzk7hWNZUe_Ly7I"

HEADERS = {
    "apikey": SERVICE_ROLE_KEY,
    "Authorization": f"Bearer {SERVICE_ROLE_KEY}",
    "Content-Type": "application/json",
    "Prefer": "resolution=ignore-duplicates"
}

def parse_insert_values(sql_content, table_name):
    """Parse INSERT statements from SQL content"""
    records = []
    
    # Find all INSERT statements
    pattern = rf"INSERT INTO {table_name} \(([^)]+)\) VALUES\s+(.+?);"
    matches = re.findall(pattern, sql_content, re.DOTALL | re.IGNORECASE)
    
    for columns_str, values_block in matches:
        columns = [c.strip() for c in columns_str.split(",")]
        
        # Parse value tuples
        values_pattern = r"\(([^)]+(?:\([^)]*\)[^)]*)*)\)"
        value_matches = re.findall(values_pattern, values_block, re.DOTALL)
        
        for values_str in value_matches:
            values = parse_values(values_str)
            if values and len(values) == len(columns):
                record = {}
                for col, val in zip(columns, values):
                    record[col] = val
                records.append(record)
    
    return records

def parse_values(values_str):
    """Parse a values string into a list"""
    values = []
    current = ""
    in_quotes = False
    depth = 0
    
    for char in values_str:
        if char == "'" and (not current or current[-1] != "\\"):
            in_quotes = not in_quotes
            current += char
        elif char == "(" and not in_quotes:
            depth += 1
            current += char
        elif char == ")" and not in_quotes:
            depth -= 1
            current += char
        elif char == "," and not in_quotes and depth == 0:
            values.append(parse_value(current.strip()))
            current = ""
        else:
            current += char
    
    if current.strip():
        values.append(parse_value(current.strip()))
    
    return values

def parse_value(val):
    """Parse a single value"""
    val = val.strip()
    
    if val == "NULL" or val == "null":
        return None
    
    if val.startswith("'") and val.endswith("'"):
        val = val[1:-1].replace("''", "'")
        return val
    
    if val.startswith("gen_random_uuid()"):
        return None  # Will be generated by database
    
    try:
        if "." in val:
            return float(val)
        return int(val)
    except ValueError:
        return val

def batch_insert(table, records, batch_size=500):
    """Insert records in batches via REST API"""
    total = len(records)
    inserted = 0
    
    for i in range(0, total, batch_size):
        batch = records[i:i + batch_size]
        
        # Convert records for REST API
        for record in batch:
            # Remove gen_random_uuid() - let DB generate it
            if 'id' in record and record['id'] is None:
                del record['id']
        
        url = f"{SUPABASE_URL}/rest/v1/{table}"
        
        try:
            response = requests.post(url, headers=HEADERS, json=batch, timeout=60)
            
            if response.status_code in [200, 201, 409]:
                inserted += len(batch)
                print(f"  ✅ {table}: {inserted}/{total} ({inserted/total*100:.1f}%)")
            else:
                print(f"  ⚠️  Batch {i}: HTTP {response.status_code}")
                print(f"     Response: {response.text[:200]}")
                
        except Exception as e:
            print(f"  ❌ Error batch {i}: {e}")
        
        time.sleep(0.1)  # Rate limiting
    
    return inserted

def count_records(table):
    """Count records in table"""
    url = f"{SUPABASE_URL}/rest/v1/{table}?select=id&limit=1"
    try:
        response = requests.head(url, headers=HEADERS, timeout=10)
        return response.headers.get('content-range', '0').split('/')[-1]
    except:
        return "?"

def main():
    print("=" * 60)
    print("FINAL MIGRATION - order_items & inventory_transactions")
    print("=" * 60)
    
    # File mapping
    files = [
        ("supabase/migrations/ready/part_005_part001.sql", "order_items"),
        ("supabase/migrations/ready/part_005_part002.sql", "order_items"),
        ("supabase/migrations/ready/part_006_part001.sql", "inventory_transactions"),
        ("supabase/migrations/ready/part_006_part002.sql", "inventory_transactions"),
    ]
    
    for filepath, table in files:
        print(f"\n📄 Processing: {filepath}")
        
        if not os.path.exists(filepath):
            print(f"  ❌ File not found: {filepath}")
            continue
        
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
        
        print(f"  📊 File size: {len(content):,} chars")
        
        # Parse records
        records = parse_insert_values(content, table)
        print(f"  📋 Found {len(records)} records")
        
        if records:
            inserted = batch_insert(table, records)
            print(f"  ✅ Inserted: {inserted} records")
    
    # Final count
    print("\n" + "=" * 60)
    print("MIGRATION COMPLETE")
    print("=" * 60)
    print(f"order_items: {count_records('order_items')} records")
    print(f"inventory_transactions: {count_records('inventory_transactions')} records")

if __name__ == "__main__":
    main()
